# Generated by Django 5.1.14 on 2025-12-10 07:33

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0060_add_allow_skip_to_task"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("ASSIGNED", "Assigned"),
                    ("ANNOTATED", "Annotated"),
                    ("WILLREVIEWED", "Willreviewed"),
                    ("REVIEWED", "Reviewed"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="UPLOADED",
                help_text="Current status of the task",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
