# Generated by Django 5.1.14 on 2025-12-11 06:11

import django.db.models.deletion
import django_fsm
from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_project_contributor"),
        ("tasks", "0061_task_status"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("ASSIGNED", "Assigned"),
                    ("ANNOTATED", "Annotated"),
                    ("WILLREVIEWED", "Willreviewed"),
                    ("REVIEWED", "Reviewed"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="UPLOADED",
                max_length=20,
                protected=True,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.projectmember",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
    ]
