# Generated by Django 5.1.15 on 2026-01-30 05:24

from django.db import migrations


class Migration(migrations.Migration):
    ignore_migration_linter = True

    dependencies = [
        ("tasks", "0062_alter_task_status_taskassignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
    ]
