# Generated by Django 5.1.14 on 2025-11-20 02:21

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_projects_soft_delete_indexes_async"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("annotator", "Annotator"),
                    ("reviewer", "Reviewer"),
                    ("project_manager", "Project Manager"),
                ],
                default="annotator",
                max_length=64,
            ),
        ),
    ]
