# Generated by Django 5.1.14 on 2025-12-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_project_contributor"),
        ("tasks", "0062_alter_task_status_taskassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="allocated_task",
            field=models.ManyToManyField(
                related_name="allocated_by", to="tasks.taskassignment"
            ),
        ),
    ]
