# Generated by Django 5.1.14 on 2025-12-11 07:42

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_projectmember_allocated_task"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name="projectmember",
            name="allocation_ratio",
            field=models.IntegerField(default=0, help_text="Allocation ratio"),
        ),
    ]
