# django-migration-linter: ignore
# Generated by Django 5.1.14 on 2025-12-15 06:12

import django.db.models.deletion
from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_projectmember_allocation_ratio"),
        ("workspaces", "__first__"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name="project",
            name="workspaces",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="workspaces.WorkSpace",
            ),
        ),
    ]
