# Generated by Django 5.1.15 on 2025-12-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_remove_project_workspaces_project_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('annotator', 'Annotator'), ('reviewer', 'Reviewer'), ('project_manager', 'Project Manager')], default='annotator', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='role',
        ),
        migrations.CreateModel(
            name='ProjectMemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_member_roles', to='projects.projectmember')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_by', to='projects.role')),
            ],
            options={
                'db_table': 'project_member_roles',
            },
        ),
        migrations.AddField(
            model_name='projectmember',
            name='role',
            field=models.ManyToManyField(related_name='project_members', through='projects.ProjectMemberRole', to='projects.role'),
        ),
    ]
