# Generated by Django 5.1.15 on 2026-01-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_project_annotator_evaluation_enabled'),
        ('projects', '0039_remove_project_workspaces_project_workspace'),
    ]

    operations = [
    ]
