# Generated by Django 5.1.15 on 2025-12-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_project_annotator_evaluation_enabled'),
        ('projects', '0040_role_remove_projectmember_role_projectmemberrole_and_more'),
    ]

    operations = [
    ]
