# Generated by Django 5.1.15 on 2025-12-17 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspace",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="workspace",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["title"], name="workspaces__title_898a9c_idx"),
        ),
    ]
