# Generated by Django 5.1.15 on 2025-12-17 05:58

from django.db import migrations


class Migration(migrations.Migration):
    ignore_migration_linter = True

    dependencies = [
        ("workspaces", "0002_alter_workspace_options_workspace_created_at_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workspace",
            new_name="workspaces_title_31d759_idx",
            old_name="workspaces__title_898a9c_idx",
        ),
        migrations.AlterModelTable(
            name="workspace",
            table="workspaces",
        ),
    ]
