# Generated by Django 5.1.15 on 2025-12-18 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workspaces",
            "0003_rename_workspaces__title_898a9c_idx_workspaces_title_31d759_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                related_name="workspaces",
                through="workspaces.WorkSpaceMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
