# Generated by Django 5.1.15 on 2025-12-23 00:24

from django.db import migrations


class Migration(migrations.Migration):
    ignore_migration_linter = True

    dependencies = [
        ('workspaces', '0004_alter_workspace_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacemember',
            old_name='is_owner',
            new_name='is_workspace_manager',
        ),
    ]
