# Generated by Django 5.1.15 on 2026-02-03 02:22

from django.db import migrations


class Migration(migrations.Migration):
    ignore_migration_linter = True

    dependencies = [
        ('workspaces', '0006_workspace_created_by_workspace_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='created_by',
        ),
    ]
