# Generated by Django 5.1.15 on 2026-01-26 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0022_normalize_localfiles_paths"),
        ("workspaces", "0006_workspace_created_by_workspace_deleted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceImportStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sync finished time",
                        null=True,
                        verbose_name="last sync",
                    ),
                ),
                (
                    "last_sync_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Count of tasks synced last time",
                        null=True,
                        verbose_name="last sync count",
                    ),
                ),
                (
                    "last_sync_job",
                    models.CharField(
                        blank=True,
                        help_text="Last sync job ID",
                        max_length=256,
                        null=True,
                        verbose_name="last_sync_job",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                        ],
                        default="initialized",
                        max_length=64,
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback report for the last failed sync",
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Meta and debug information about storage processes",
                        null=True,
                        verbose_name="meta",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage title",
                        max_length=256,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "synchronizable",
                    models.BooleanField(
                        default=True,
                        help_text="If storage can be synced",
                        verbose_name="synchronizable",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkspaceLocalFilesImportStorage",
            fields=[
                (
                    "localfilesmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="io_storages.localfilesmixin",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sync finished time",
                        null=True,
                        verbose_name="last sync",
                    ),
                ),
                (
                    "last_sync_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Count of tasks synced last time",
                        null=True,
                        verbose_name="last sync count",
                    ),
                ),
                (
                    "last_sync_job",
                    models.CharField(
                        blank=True,
                        help_text="Last sync job ID",
                        max_length=256,
                        null=True,
                        verbose_name="last_sync_job",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                        ],
                        default="initialized",
                        max_length=64,
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback report for the last failed sync",
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Meta and debug information about storage processes",
                        null=True,
                        verbose_name="meta",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage title",
                        max_length=256,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "synchronizable",
                    models.BooleanField(
                        default=True,
                        help_text="If storage can be synced",
                        verbose_name="synchronizable",
                    ),
                ),
                (
                    "recursive_scan",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Perform recursive scan over the directory content",
                        null=True,
                        verbose_name="recursive scan",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="A unique integer value identifying this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("io_storages.localfilesmixin", models.Model),
        ),
    ]
