# Generated by Django 5.1.15 on 2026-01-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0023_workspaceimportstorage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localfilesimportstorage",
            name="parent_storage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                db_index=False,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_storage",
                to="io_storages.workspacelocalfilesimportstorage",
            ),
        ),
    ]
