# Generated by Django 5.1.15 on 2026-02-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0026_alter_localfilesimportstorage_parent_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfilesimportstorage',
            name='parent_storage',
            field=models.ForeignKey(blank=True, null=True, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='sub_storage', to='io_storages.workspacelocalfilesimportstorage'),
        ),
    ]
