name: Check for broken links

on:
  pull_request:
    branches: ["develop"]
    types: [synchronize, opened]
    paths:
      - "docs/**"
      - ".github/workflows/link-check.yml"
  workflow_dispatch:

jobs:
  check_links:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install broken-link-checker

      - name: Run broken-link-checker for Label Studio Docs
        run: |
          URL="https://deploy-preview-${{ github.event.pull_request.number }}--label-studio-docs-new-theme.netlify.app"
          echo "Checking: $URL"
          if ! curl -f -s -o /dev/null "$URL"; then
            echo "Netlify deploy preview is not available. Skipping link check."
            exit 0
          fi
          npx blc "$URL" -roef --exclude "/api" --filter-level 0

      - name: Run broken-link-checker for Human Signal Docs
        run: |
          URL="https://deploy-preview-${{ github.event.pull_request.number }}--heartex-docs.netlify.app"
          echo "Checking: $URL"
          if ! curl -f -s -o /dev/null "$URL"; then
            echo "Netlify deploy preview is not available. Skipping link check."
            exit 0
          fi
          npx blc "$URL" -roef --exclude "/api" --filter-level 0
